apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - env: dev
          cluster: in-cluster
        - env: staging
          cluster: in-cluster
        - env: prod
          cluster: in-cluster
  template:
    metadata:
      name: 'guestbook-simple-{{env}}'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/HardsonTsi/clown.git
        targetRevision: env/{{env}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: 'guestbook-simple-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
